# GITHUB RUNNER - Combined Manifests
# https://github.com/davift/github-actions

# namespace.yaml
kind: Namespace
apiVersion: v1
metadata:
  name: runner
  labels:
    name: runner

---

# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: runner-app-${ENV}
  namespace: runner
spec:
  # This application shall only have one instance
  replicas: 2
  selector:
    matchLabels:
      app: runner-app-${ENV}
  template:
    metadata:
      labels:
        app: runner-app-${ENV}
    spec:
      containers:
      - name: runner-app-${ENV}
        image: localhost:32000/runner:${ENV}

