name: Deploy on Merge to Main

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:

      - name: Run a command
        run: |
          /usr/local/bin/kubectl get nodes
          
