name: Deploy on Merge to Main

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      # Sanity check
      - name: Run
        run: |
          /usr/local/bin/kubectl get nodes

      # When self-hosting this is necessary
      - name: Checkout repo
        uses: actions/checkout@v4

      # Parsing files list
      - name: List of changed files
        id: changed-files
        uses: tj-actions/changed-files@v39
      - name: String to multiline
        id: convert
        run: |
          echo 'MULTILINE<<EOF' >> $GITHUB_ENV
          echo "${{ steps.changed-files.outputs.all_changed_files }}" | tr " " "\n" >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV

      # Applying only changed manifests
      - if: ${{ env.MULTILINE != '' }}
        name: Applying
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            if [[ $file == *.yaml && $file != .github/workflows/* ]]; then
              /usr/local/bin/kubectl apply -f $file
            else
              echo "Nothing to deploy"
            fi
          done
