name: Deploy on Merge to Main

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      # Sanity check
      - name: Run a command
        run: |
          /usr/local/bin/kubectl get nodes

      # When self-hosting this is necessary
      - name: Get the whole repo
        uses: actions/checkout@v4

      # Getting and applying only changed manifests
      - name: Get a list of changed files
        id: changed-files
        uses: tj-actions/changed-files@v39

      - name: Convert string to multiline
        id: convert
        run: |
          echo 'MULTILINE<<EOF' >> $GITHUB_ENV
          echo "${{ steps.changed-files.outputs.all_changed_files }}" | tr " " "\n" >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV

      - if: ${{ env.MULTILINE != '' }}
        name: Showing files
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            if [[ $file == *.yaml ]]; then
              /usr/local/bin/kubectl apply -f $file
            fi
          done
