name: Dev Build Artifacts and Deploying

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: self-hosted-non-prod

    steps:
      # Sanity check
      - name: Run
        run: |
          /usr/bin/docker images

      # When self-hosting this is necessary
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      # Parsing files list
      - name: List of changed files
        id: changed-files
        uses: tj-actions/changed-files@v39
      - name: String to multiline
        id: convert
        run: |
          echo 'MULTILINE<<EOF' >> $GITHUB_ENV
          echo "${{ steps.changed-files.outputs.all_changed_files }}" | tr " " "\n" >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV

      # Applying only changed files
      - if: ${{ env.MULTILINE != '' }}
        name: Applying
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            if [[ $file == */Dockerfile ]]; then
              echo "Building: $file"
              sed -i "s/<TOKEN>/${{ secrets.TOKEN }}/g" $file
              /usr/bin/docker build $(dirname "$file") -t 10.10.10.100:32000/$(dirname $(dirname "$file")):dev
              echo "Pushing..."
              /usr/bin/docker push 10.10.10.100:32000/$(dirname $(dirname "$file")):dev
            fi
          done
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            if [[ $file == *.yaml && $file != .github/workflows/* ]]; then
              echo "Deploying: $file"
              /usr/local/bin/kubectl apply -f <(sed "s/\${ENV}/dev/g" $file)
            fi
          done
