name: Deploy Manifests

on:
  # Only runs when the previous workflow is completed
  workflow_run:
    workflows: ["Build Artifacts"]
    types:
      - completed
  # This workflow can be manually triggered
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted-prod

    steps:
      # Sanity check
      - name: Run
        run: |
          /usr/local/bin/kubectl get nodes

      # When self-hosting this is necessary
      - name: Checkout repo
        uses: actions/checkout@v4

      # Parsing files list
      - name: List of changed files
        id: changed-files
        uses: tj-actions/changed-files@v39
      - name: String to multiline
        id: convert
        run: |
          echo 'MULTILINE<<EOF' >> $GITHUB_ENV
          echo "${{ steps.changed-files.outputs.all_changed_files }}" | tr " " "\n" >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV

      # Applying only changed files
      - if: ${{ env.MULTILINE != '' }}
        name: Applying
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            if [[ $file == *.yaml && $file != .github/workflows/* ]]; then
              echo "Deploying: $file"
              /usr/local/bin/kubectl apply -f <(sed "s/\${ENV}/stage/g" $file)
            fi
          done
